'use strict';
const $ = id => document.getElementById(id);
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines = value => value.split('\n').map(s=>s.trim()).filter(Boolean);
const stamp = value => new Date(value * 1000).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const statuses = {idle:'待讨论',planning:'预研中',ready:'待审阅',running:'执行中',verified:'验证通过',needs_human:'待人工验收',blocked:'执行受阻',cancelled:'已停止',error:'预研未完成',interrupted:'已中断',incomplete:'旧版记录'};
const hash = location.hash.slice(1);
if (hash && !['workspace','history','settings','help'].includes(hash)) sessionStorage.setItem('router-token', hash);
history.replaceState(null,'',location.pathname);
const state = {token:sessionStorage.getItem('router-token')||'',boot:null,c:null,rows:[],attachments:[],advanced:false,dirty:false,revision:null,requesting:false,polling:false};
let toastTimer;
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
async function api(path,data){const r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{'X-Router-Token':state.token,...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw new Error(body.error||'操作未完成');return body;}
function action(fn){return async e=>{try{await fn(e);}catch(error){toast(error.message);}};}
function scrollBottom(){$('scroll-area').scrollTop=$('scroll-area').scrollHeight;}
function currentProposal(){return state.c?.proposals.find(p=>p.revision===state.revision)||state.c?.proposals.at(-1);}
function busy(){return state.c && ['planning','running'].includes(state.c.status);}
function draftKey(){return 'router-draft-'+(state.c?.id||'new');}
function saveLocalDraft(){sessionStorage.setItem(draftKey(),JSON.stringify({message:$('request').value,repo:$('repo').value,project:$('project').value}));if(state.dirty&&currentProposal())sessionStorage.setItem('router-edits-'+state.c.id,JSON.stringify({revision:state.revision,edits:collectEdits()}));}
function restoreLocalDraft(){const raw=sessionStorage.getItem(draftKey());if(raw){try{const d=JSON.parse(raw);$('request').value=d.message||'';$('repo').value=d.repo||'';$('project').value=d.project||'';}catch{}}}
async function refreshHistory(){state.rows=(await api('conversations')).conversations;renderHistory();}
function renderHistory(){const q=$('history-search').value.toLowerCase();const rows=state.rows.filter(r=>(r.title+' '+r.project).toLowerCase().includes(q));$('history-count').textContent=state.rows.length;$('conversations').innerHTML=rows.map(r=>`<button class="history-item ${state.c?.id===r.id?'active':''}" data-chat="${escape(r.id)}" ${r.legacy?'data-legacy="true"':''}><strong>${escape(r.title)}</strong><small>${escape(r.project||statuses[r.status]||r.status)} · ${stamp(r.updated)}</small></button>`).join('')||'<p class="hint">这里会留下你的需求与方案。</p>';}
async function openChat(id){saveLocalDraft();const c=await api('conversations/'+id);state.c=c;state.attachments=c.attachments||[];state.dirty=false;state.revision=c.proposals.at(-1)?.revision;$('repo').value=c.repo||'';$('project').value=c.project||'';$('request').value='';sessionStorage.setItem('router-current',id);resetAdvancedFields();restoreLocalDraft();renderConversation();renderAttachments();renderHistory();document.body.classList.remove('sidebar-open');const saved=sessionStorage.getItem('router-edits-'+id);if(saved){try{const d=JSON.parse(saved);if(d.revision===state.revision){applyEdits(d.edits);state.dirty=true;}}catch{}}scrollBottom();}
function resetAdvancedFields(){$('web-research').checked=false;$('public-queries').value='';$('public-urls').value='';for(const id of ['allowed','forbidden','acceptance','profile'])$(id).value='';$('mode').value='balanced';document.querySelectorAll('#checks input').forEach(x=>x.checked=false);}
function newChat(){saveLocalDraft();state.c=null;state.revision=null;state.dirty=false;state.attachments=[];$('request').value='';$('repo').value='';$('project').value='';resetAdvancedFields();sessionStorage.removeItem('router-current');restoreLocalDraft();renderConversation();renderHistory();renderAttachments();document.body.classList.remove('sidebar-open');$('request').focus();}
function renderConversation(){const c=state.c;$('welcome').hidden=!!c;$('chat-title').textContent=c?.title||'新需求';$('project-label').textContent=c?.project||'';$('messages').innerHTML=(c?.messages||[]).map(m=>`<article class="message ${m.role==='user'?'user':'assistant'}"><div class="role">${m.role==='user'?'你':'Model Router'} · ${stamp(m.time)}</div><p>${escape(m.content)}</p>${m.revision?`<button class="quiet" data-version="${m.revision}">查看方案 v${m.revision}</button>`:''}</article>`).join('');renderProposal();renderPublications();renderPhase();}
function bullet(title,items){return items?.length?`<h3>${escape(title)}</h3><ul>${items.map(s=>`<li>${escape(s)}</li>`).join('')}</ul>`:'';}
function field(id,title,value,rows=3,cls=''){return `<label>${title}<textarea id="${id}" class="${cls}" rows="${rows}">${escape(Array.isArray(value)?value.join('\n'):value)}</textarea></label>`;}
function renderProposal(){const p=currentProposal();$('proposal').hidden=!p;if(!p){$('proposal').innerHTML='';return;}const published=state.c.publications.some(x=>x.revision===p.revision);const historic=p.revision!==state.c.proposals.at(-1).revision;
 $('proposal').innerHTML=`<article class="proposal-card"><div class="proposal-heading"><h2>${escape(p.title)}</h2><span class="badge">${p.source==='template'?'基础模板':'预研方案'} · v${p.revision}</span></div><div class="proposal-body">${p.source==='template'?'<p class="notice">尚未连接分析模型。这是基础模板；在设置连接 DeepSeek 后，继续发送需求即可进行两轮预研。</p>':''}${bullet('预研结论',p.research)}<details><summary>研究依据、假设与待确认事项</summary>${bullet('实际资料来源',p.sources)}${bullet('采用的假设',p.assumptions)}${bullet('待确认事项（可继续聊天补充）',p.questions)}${bullet('当前边界',p.limitations)}</details><label>执行模型<select id="p-model">${state.boot.models.map(m=>`<option value="${escape(m.id)}" ${m.id===p.recommended_model?'selected':''}>${escape(m.model)}${m.reasoning?' · '+escape(m.reasoning):''} (${escape(m.provider)})</option>`).join('')}</select></label><p class="reason">${escape(p.model_reason)}<br>${escape((p.policy_reasons||[]).join('；'))}</p>${field('p-prompt','任务 Prompt · 点击即可编辑',p.execution_prompt,12,'prompt')}<p class="hint">发布将使用这里的正文，并附加已审阅的范围与系统预算约束。</p><details open><summary>拟修改文件与验收标准</summary>${field('p-files','文件计划与用途',p.file_plan)}${field('p-acceptance','验收标准',p.acceptance_criteria)}</details><details><summary>权限与 Codex 插件建议</summary><p class="permission-summary">实际权限：独立候选目录 · 按范围写入 · 原工程不自动改动。Codex 可在沙箱内执行命令；DeepSeek 可运行已配置检查。外部网络与插件连接当前关闭。</p><div class="grid">${field('p-allowed','允许修改（自动拟定；* 表示候选目录内文件）',p.allowed_files)}${field('p-forbidden','禁止修改',p.forbidden_files)}</div>${field('p-permissions','建议给予的权限与原因（建议说明）',p.permissions_notes)}${field('p-plugins','建议使用的插件与用途（当前未接入）',p.plugins)}<p class="hint">插件建议可用于在 Codex 中手动准备任务；编辑此说明不会自动安装插件或扩大权限。</p>${field('p-checks','采用的已配置检查（每行一个名称）',p.checks,2)}</details></div><div class="proposal-footer"><span class="revision-note">${historic?'历史版本 · 只读':published?'此版本已发布 · 修改后可生成新版本':'审阅后发布 · 不会自动开始执行'}</span><button id="preview-prompt" class="quiet">完整 Prompt</button><button id="save-proposal">保存修改</button><button id="publish" class="primary">发布此方案 →</button></div></article>`;
 $('proposal').querySelectorAll('input,textarea,select').forEach(el=>{el.disabled=historic||busy();el.addEventListener('input',()=>{state.dirty=true;saveLocalDraft();$('publish').disabled=false;});});$('save-proposal').disabled=historic||busy();$('publish').disabled=historic||busy()||published;$('preview-prompt').disabled=historic||busy();$('save-proposal').onclick=action(async()=>{await saveProposal();toast('修改已保存为方案版本');});$('preview-prompt').onclick=action(async()=>{const r=await saveProposal();$('full-prompt').textContent=r.full_prompt;$('prompt-dialog').showModal();});$('publish').onclick=action(publish);
 const picker=document.createElement('label');picker.innerHTML='方案版本<select id="proposal-version">'+state.c.proposals.map(v=>'<option value="'+v.revision+'" '+(v.revision===p.revision?'selected':'')+'>v'+v.revision+' · '+stamp(v.created)+(state.c.publications.some(x=>x.revision===v.revision)?' · 已发布':'')+'</option>').join('')+'</select>';$('proposal').querySelector('.proposal-body').prepend(picker);$('proposal-version').onchange=action(async e=>{const version=Number(e.target.value);if(state.dirty)await saveProposal();state.revision=version;renderProposal();});
}
const editFields={'execution_prompt':'p-prompt','recommended_model':'p-model','file_plan':'p-files','allowed_files':'p-allowed','forbidden_files':'p-forbidden','acceptance_criteria':'p-acceptance','checks':'p-checks','plugins':'p-plugins','permissions_notes':'p-permissions'};
function collectEdits(){return Object.fromEntries(Object.entries(editFields).map(([k,id])=>[k,['execution_prompt','recommended_model'].includes(k)?$(id).value:lines($(id).value)]));}
function applyEdits(edits){Object.entries(editFields).forEach(([key,id])=>{if($(id)&&edits[key]!==undefined)$(id).value=Array.isArray(edits[key])?edits[key].join('\n'):edits[key];});}
async function saveProposal(){const cid=state.c.id;const r=await api('proposal',{conversation_id:cid,revision:state.revision,edits:collectEdits()});if(state.c?.id!==cid)return r;state.dirty=false;sessionStorage.removeItem('router-edits-'+cid);state.c=await api('conversations/'+cid);state.revision=r.proposal.revision;renderProposal();return r;}
async function publish(){if(state.requesting)return;state.requesting=true;$('publish').disabled=true;try{await saveProposal();await api('publish',{conversation_id:state.c.id,revision:state.revision});state.c=await api('conversations/'+state.c.id);renderConversation();await refreshHistory();scrollBottom();}finally{state.requesting=false;if($('publish'))$('publish').disabled=busy()||state.c?.publications.some(p=>p.revision===state.revision);}}
function renderPhase(){$('phase').hidden=!state.c?.phase;$('phase').textContent=state.c?.phase||'';$('phase').className='phase'+(busy()?' working':'')+(state.c?.status==='error'?' error':'');$('send').disabled=!!busy()||state.requesting;$('stop').hidden=!busy();$('send').textContent=state.c?'继续讨论并更新 ↑':'研究并生成方案 ↑';}
function renderPublications(){$('publications').innerHTML=(state.c?.publications||[]).map(p=>`<article class="publication"><h3>发布记录 · 方案 v${p.revision} <span class="badge">${escape(statuses[p.status]||p.status)}</span></h3><p>${stamp(p.time)}${p.error?' · '+escape(p.error):''}${p.result?' · '+escape(p.result.reason||''):''}</p>${p.status==='running'?'<div id="live-events" class="live-events">正在准备执行环境…</div>':''}${p.run_id?`<button data-execution="${escape(p.run_id)}">查看具体执行记录</button><button data-output="${escape(p.run_id)}" class="quiet">打开成果文件夹</button>`:''}</article>`).join('');}
function renderAttachments(){$('attachments').innerHTML=state.attachments.map((a,i)=>`<button type="button" data-remove="${i}" aria-label="移除 ${escape(a.name)}">${escape(a.name)} ×</button>`).join('');}
function eventText(e){const d=e.data||{};return e.kind==='summary'?d.text:e.kind==='file_read'?'读取 '+d.path:e.kind==='file_write'?'修改 '+d.path:e.kind==='test'?(d.passed?'检查通过：':'检查失败：')+(d.name||'') :e.kind==='tool'?(d.command||d.signature||'执行工具'):e.kind==='session'?'Codex 会话 '+d.thread_id:e.kind==='usage'?'本轮用量 '+(d.tokens??'未知')+' tokens':e.kind==='hypothesis'?d.text:null;}
async function execution(id){const r=await api('executions/'+id);$('execution-content').innerHTML=`<p class="notice">${escape(statuses[r.result?.status]||'执行记录')} · ${escape(r.result?.reason||'')}<br>运行编号 ${escape(id)}</p><div class="artifact-buttons"><button data-output="${id}">打开成果文件夹</button>${r.sessions.map(s=>`<button data-resume="${escape(s)}" data-run="${id}">打开 Codex 会话 · ${escape(s.slice(0,8))}</button>`).join('')}${r.result?.status==='verified'&&!r.promoted?`<button data-promote="${id}">将验证通过的修改应用到源目录</button>`:''}</div>${r.sessions.length?'<p class="hint">使用本机 Codex CLI 恢复这一条会话；旧版临时会话可能未保留。</p>':'<p class="hint">该运行的具体执行过程保存在下方；没有可恢复的 Codex 会话。</p>'}<details><summary>成果文件清单（${r.outputs.length}）</summary><pre>${escape(r.outputs.join('\n')||'暂无文件')}</pre></details><div class="artifact-buttons">${r.files.map(n=>`<button data-artifact="${escape(n)}" data-run="${id}">${escape(n)}</button>`).join('')}</div><pre id="artifact-content" hidden></pre><h3>执行消息与工具记录</h3>${r.events.map(e=>{const text=eventText(e);return text?`<div class="transcript"><strong>尝试 ${e.attempt||1} · ${escape(e.kind)}</strong>${escape(text)}</div>`:'';}).join('')||'<p class="hint">暂无执行消息。</p>'}`;if(!$('execution-dialog').open)$('execution-dialog').showModal();}
async function loadSettings(){state.boot=await api('bootstrap');const b=state.boot,s=b.settings;loadCatalogSettings(s);for(const [id,key] of Object.entries({'ds-model':'deepseek_model','sol-model':'sol_model','astra-model':'astra_model','codex-command':'codex_command','thinking':'thinking','max-minutes':'max_minutes','max-attempts':'max_attempts'}))$(id).value=s[key];$('quota').value=s.quota??'';$('auto-usage').checked=s.auto_usage;$('remember-key').checked=b.key_saved;$('command-settings').value=JSON.stringify(s.commands,null,2);$('connection-status').textContent=`DeepSeek：${b.key_present?'已连接':'未连接（可生成基础模板）'} · Codex：${b.codex_present?'已找到本机程序':'未找到程序'}`;$('checks').innerHTML=Object.keys(s.commands).map(name=>`<label class="checkbox"><input type="checkbox" value="${escape(name)}">${escape(name)}</label>`).join('');}
function advanced(on){state.advanced=on;$('advanced').hidden=!on;$('advanced-tab').classList.toggle('selected',on);$('simple-tab').classList.toggle('selected',!on);$('advanced-tab').setAttribute('aria-pressed',on);$('simple-tab').setAttribute('aria-pressed',!on);}
$('composer').onsubmit=action(async e=>{e.preventDefault();if(state.requesting||busy())return;state.requesting=true;renderPhase();try{if(state.dirty)await saveProposal();const options={web_research:$('web-research').checked,public_queries:lines($('public-queries').value),public_urls:lines($('public-urls').value)};if(state.advanced){options.mode=$('mode').value;options.allowed_files=lines($('allowed').value);options.forbidden_files=lines($('forbidden').value);options.acceptance_criteria=lines($('acceptance').value);options.checks=[...document.querySelectorAll('#checks input:checked')].map(x=>x.value);if($('profile').value.trim())options.profile=JSON.parse($('profile').value);}const r=await api('message',{conversation_id:state.c?.id,message:$('request').value,repo:$('repo').value,project:$('project').value,attachments:state.attachments,options});$('request').value='';sessionStorage.removeItem(draftKey());state.c=await api('conversations/'+r.conversation_id);state.revision=state.c.proposals.at(-1)?.revision;sessionStorage.setItem('router-current',r.conversation_id);renderConversation();await refreshHistory();scrollBottom();}finally{state.requesting=false;renderPhase();}});
$('request').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('composer').requestSubmit();}});
$('request').oninput=saveLocalDraft;$('repo').oninput=saveLocalDraft;$('project').oninput=saveLocalDraft;
$('new-chat').onclick=newChat;$('history-search').oninput=renderHistory;$('simple-tab').onclick=()=>advanced(false);$('advanced-tab').onclick=()=>advanced(true);$('menu-toggle').onclick=()=>document.body.classList.toggle('sidebar-open');
$('attach').onclick=()=>$('file-input').click();$('file-input').onchange=action(async()=>{const added=[];for(const file of $('file-input').files){if(file.size>100000)throw new Error('单份文本资料最多100 KB');added.push({name:file.name,content:await file.text()});}const next=[...state.attachments,...added];if(next.length>8||next.reduce((s,a)=>s+a.content.length,0)>50000)throw new Error('最多8份资料，文本合计不超过50000字');state.attachments=next;renderAttachments();$('file-input').value='';});
$('stop').onclick=action(async()=>{if(state.c.status==='planning')await api('stop-research',{conversation_id:state.c.id});else{const p=state.c.publications.findLast(p=>p.status==='running');if(p)await api('cancel',{job_id:p.job_id});}toast('已请求停止，正在保存记录');});
$('settings-open').onclick=action(async()=>{await loadSettings();$('settings-dialog').showModal();document.body.classList.remove('sidebar-open');});for(const prefix of ['settings','execution','prompt'])$(prefix+'-close').onclick=()=>$(prefix+'-dialog').close();
function guide(on){$('guide').hidden=!on;$('settings-form').hidden=on;$('guide-tab').classList.toggle('selected',on);$('models-tab').classList.toggle('selected',!on);}$('guide-tab').onclick=()=>guide(true);$('models-tab').onclick=()=>guide(false);
$('settings-form').onsubmit=action(async e=>{e.preventDefault();await api('settings',{api_key:$('api-key').value,remember_key:$('remember-key').checked,deepseek_model:$('ds-model').value,sol_model:$('sol-model').value,astra_model:$('astra-model').value,codex_command:$('codex-command').value,thinking:$('thinking').value,auto_usage:$('auto-usage').checked,quota:$('quota').value===''?null:Number($('quota').value),max_minutes:Number($('max-minutes').value),max_attempts:Number($('max-attempts').value),commands:JSON.parse($('command-settings').value)});$('api-key').value='';await loadSettings();toast('设置已保存');});
$('usage').onclick=action(async()=>{const r=await api('usage',{});$('quota').value=r.remaining??'';toast(r.remaining===null?'暂时无法读取额度':'剩余额度 '+r.remaining+'%');});$('shutdown').onclick=action(async()=>{await api('shutdown',{});toast('本地服务已退出，下次双击桌面图标即可打开');});
document.addEventListener('click',action(async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.chat){if(b.dataset.legacy)await execution(b.dataset.chat);else await openChat(b.dataset.chat);}if(b.dataset.example){$('request').value=b.dataset.example;$('request').focus();}if(b.dataset.remove!==undefined){state.attachments.splice(Number(b.dataset.remove),1);renderAttachments();}if(b.dataset.version){if(state.dirty)await saveProposal();state.revision=Number(b.dataset.version);renderProposal();$('proposal').scrollIntoView({block:'start'});}if(b.dataset.execution)await execution(b.dataset.execution);if(b.dataset.output)await api('open-execution',{run_id:b.dataset.output});if(b.dataset.resume)await api('open-execution',{run_id:b.dataset.run,target:'codex',session_id:b.dataset.resume});if(b.dataset.artifact){const r=await api('artifact?run='+b.dataset.run+'&name='+encodeURIComponent(b.dataset.artifact));$('artifact-content').hidden=false;$('artifact-content').textContent=r.content+(r.truncated?'\n[内容已截断]':'');}if(b.dataset.promote){if(confirm('将此运行中通过验证的修改应用到源目录？这会修改源文件。')){await api('promote',{run_id:b.dataset.promote});toast('修改已应用到源目录');await execution(b.dataset.promote);}}}));
async function poll(){if(state.polling||state.requesting)return;state.polling=true;try{await refreshHistory();const id=state.c?.id;if(id&&busy()){const old=state.c,c=await api('conversations/'+id);if(state.c?.id!==id)return;state.c=c;if(c.messages.length!==old.messages.length||c.proposals.length!==old.proposals.length){state.revision=c.proposals.at(-1)?.revision;renderConversation();scrollBottom();}else{renderPhase();renderPublications();if(c.status!==old.status&&!state.dirty)renderProposal();}const p=c.publications.findLast(p=>p.status==='running');if(p){try{const j=await api('jobs/'+p.job_id);if(state.c?.id===id&&$('live-events'))$('live-events').textContent=j.events.map(eventText).filter(Boolean).slice(-10).join('\n')||'执行器正在处理任务…';}catch{}}}}catch(error){if(state.c&&busy()){$('phase').textContent='连接暂时中断，正在重试；已保存的会话可在重开后查看。';}}finally{state.polling=false;}}
window.addEventListener('beforeunload',saveLocalDraft);
(async()=>{try{await loadSettings();await refreshHistory();const id=sessionStorage.getItem('router-current');if(id&&state.rows.some(c=>c.id===id&&!c.legacy))await openChat(id);else{restoreLocalDraft();renderConversation();}setInterval(poll,2200);}catch(error){toast(error.message);$('phase').hidden=false;$('phase').textContent=error.message;}})();

function loadCatalogSettings(s){
 $('provider-settings').value=JSON.stringify(s.providers,null,2);
 $('catalog-settings').value=JSON.stringify(s.models,null,2);
 $('evaluation-settings').value=JSON.stringify(s.evaluation_records||[],null,2);
 $('analyzer-provider').value=s.analyzer_provider;$('analyzer-model').value=s.analyzer_model;
 $('discover-provider').innerHTML=Object.keys(s.providers).map(p=>`<option value="${escape(p)}">${escape(p)}</option>`).join('');
}
$('discover-models').onclick=action(async()=>{
 $('discovery-result').hidden=false;$('discovery-result').textContent='正在查询供应商…';
 const value=await api('catalog/discover',{provider:$('discover-provider').value});
 $('discovery-result').textContent=JSON.stringify(value,null,2);
});
$('save-catalog').onclick=action(async()=>{
 await api('settings',{providers:JSON.parse($('provider-settings').value),models:JSON.parse($('catalog-settings').value),
  evaluation_records:JSON.parse($('evaluation-settings').value),analyzer_provider:$('analyzer-provider').value,analyzer_model:$('analyzer-model').value});
 await loadSettings();toast('模型目录与评测已保存；没有自动启动执行');
});
